### ISSUE TITLE
Missing  `"module": "preserve"` for bundler?

### ISSUE THREAD

**Issue by chungweileong94** [total-typescript/tsconfig#1]
Was it a mistake or there is a reason why we are not using `"module": "preserve"` for bundler? 

References:
- https://www.totaltypescript.com/tsconfig-cheat-sheet#not-transpiling-with-typescript
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler

**Comment by chungweileong94** [comment]
A bit of context, I personally use a lot of non-tsc toolings like `tsx`, `bunchee` & etc, so I use `"module": "preserve"` most of the time. I'm not sure if there are cases where we might not want to use `"module": "preserve"` for non-tsc or typescript version below v5.

**Comment by mattpocock** [comment]
100% a mistake, and a bizarre one. Thanks for the issue, fixed in 1.0.3.

**Comment by kporten** [comment]
When I use the following `tsconfig.json`, then VSCode provides `.js` extensions for all file imports (path auto-completion), even if I have only `.ts` files in my project:
 
```json
{
  "extends": "@total-typescript/tsconfig/bundler/no-dom"
}
```

<img width="938" alt="SCR-20240526-gtgb" src="https://github.com/total-typescript/tsconfig/assets/1839345/dca36e46-7b2d-4c42-bb0c-00fb6c6ac311">

I can get TypeScript imports back, when I change the `tsconfig.json` to:

```json
{
  "extends": "@total-typescript/tsconfig/bundler/no-dom",
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler"
  }
}
```

<img width="926" alt="SCR-20240526-gvyt" src="https://github.com/total-typescript/tsconfig/assets/1839345/77ed2d2e-f83c-40fa-98c2-36b2e27ba440">

**Comment by mattpocock** [comment]
@kporten Could you provide a reproduction? Code looks fine to me.

**Comment by kporten** [comment]
Yes, here you can find the reproduction: https://github.com/kporten/reproduction-tsconfig-vscode/tree/main

In https://github.com/kporten/reproduction-tsconfig-vscode/blob/main/src/index.ts a note explains how to get the `.js` auto-completions instead of the `.ts` files.

**Comment by mattpocock** [comment]
@kporten Thanks, I also repeated your findings.

This seems like an upstream TypeScript issue to me. Appears that just having "module: preserve" isn't enough to fix these auto imports.

Raise something there and link this issue.
