### ISSUE TITLE
What about the `incremental` option?

### ISSUE THREAD

**Issue by GermanJablo** [total-typescript/tsconfig#15]
I saw that @anthonyshew recommends using `incremental: true` and also found [this tweet](https://x.com/mattpocockuk/status/1681247039504494592) of yours:

![image](https://github.com/user-attachments/assets/304cc437-f2c5-4b91-b257-a9cbdb0b5a54)

It's not clear to me what the difference is between `incremental` and `composite`. It seems that both use some kind of cache to build faster. Should we use both? Just one?

**Comment by mattpocock** [comment]
I've found TypeScript's cache to be relatively unreliable. Composite has to be used in monorepos, but with incremental I don't think the juice is worth the squeeze.

**Comment by GermanJablo** [comment]
Ok thanks a lot for sharing your experience!

Slightly related topic: I saw a video of you configuring `tsup` on a monolith, and another one where you configure `tsc` on a monorepo. But it seems that [you can't use `tsup` with `composite`](https://github.com/egoist/tsup/issues/647#issuecomment-1280651356), right? What's your advice in that case? use `tsc + composite` or `tsup`?

**Comment by anthonyshew** [comment]
I've also seen `incremental` be weird sometimes. I'm not sure that I recommend it anymore.

**Comment by GermanJablo** [comment]
Just for the record, I just discovered that "Incremental compiles are enabled by default when using the composite flag for project references" ([source](https://github.com/microsoft/Typescript/wiki/Performance#incremental-project-emit)).
So if you're using `composite`, you're using `incremental`.

**Comment by karlhorky** [comment]
Nice, [just was thinking the same thing today](https://x.com/karlhorky/status/1845488535991947654) - cool to have this additional context!

Maybe these details should go into [The TSConfig Cheat Sheet](https://www.totaltypescript.com/tsconfig-cheat-sheet)?
