### ISSUE TITLE
outDir causes issue

### ISSUE THREAD

**Issue by dobeerman** [total-typescript/tsconfig#3]
We’re building Lambda functions with AWS CDK, which defaults to using `cdk.out/*` as its `outDir`. This hardcoded `outDir` makes it difficult to redefine.

Should we remove this hardcoded value to allow for custom `outDir` configurations?

P.S. Maybe I'm missing something? Open to suggestions!

**Comment by mattpocock** [comment]
I strongly agree - I should have removed it before releasing. I'll fix this in a patch when I get back to my laptop, or I'll accept a PR fixing it.

**Comment by mattpocock** [comment]
Will close when I release the PR with changes: #4

**Comment by mattpocock** [comment]
Released
