### ISSUE TITLE
Cannot find module without extension

### ISSUE THREAD

**Issue by ASgmbv** [total-typescript/tsconfig#5]
I'm currently developing a Node.js backend using TypeScript. However, I've encountered an issue where TypeScript doesn't recognize my imported files unless they include their extensions. Surprisingly, it recognizes files with a .js extension even if they are TypeScript files (.ts). 

Any assistance on resolving this issue would be greatly appreciated!

<img width="1159" alt="Screenshot 2024-05-14 at 21 08 22" src="https://github.com/total-typescript/tsconfig/assets/38725027/60a288cf-3e49-41b3-8dcf-85e79309df6b">

This is my tsconfig:
<img width="971" alt="Screenshot 2024-05-14 at 21 07 29" src="https://github.com/total-typescript/tsconfig/assets/38725027/5394d6b0-0eed-4994-85c4-5a356905d327">

**Comment by mattpocock** [comment]
https://www.youtube.com/watch?v=8ORIzvgNWhU

**Comment by ASgmbv** [comment]
Thank you! Your channel is a gem
